#!/usr/bin/env python3
"""Generate RSC-style DOCX and PDF reports from Smart Lab outputs."""

from __future__ import annotations

import argparse
import csv
import datetime as dt
from pathlib import Path
from typing import Iterable

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Inches, Pt
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Image, PageBreak, Paragraph, SimpleDocTemplate, Spacer

from smart_lab.config import DEFAULT_OUTPUT_DIR


def read_csv_rows(path: Path) -> list[dict]:
    if not path.exists() or path.stat().st_size == 0:
        return []
    with path.open("r", newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def parse_float(value: str | None) -> float | None:
    if value in {None, "", "None", "nan"}:
        return None
    try:
        return float(value)
    except ValueError:
        return None


def format_value(value: str | float | None, digits: int = 4) -> str:
    numeric = parse_float(str(value)) if value is not None else None
    if numeric is None:
        return "not determined"
    return f"{numeric:.{digits}g}"


def setup_docx_styles(document: Document) -> None:
    styles = document.styles
    styles["Normal"].font.name = "Times New Roman"
    styles["Normal"].font.size = Pt(11)
    for style_name in ["Title", "Heading 1", "Heading 2"]:
        styles[style_name].font.name = "Times New Roman"
    styles["Title"].font.size = Pt(18)
    styles["Heading 1"].font.size = Pt(14)
    styles["Heading 2"].font.size = Pt(12)


def title_for_report(results: list[dict], report_kind: str, report_date: str) -> str:
    types = sorted({row.get("experiment_type", "") for row in results if row.get("experiment_type")})
    type_text = ", ".join(types[:4]) if types else "Spectroscopy"
    return f"{report_kind.title()} Smart Lab Report: {type_text} Analysis ({report_date})"


def abstract_text(results: list[dict], trends: list[str]) -> str:
    analyzed = [row for row in results if row.get("status") == "analyzed"]
    types = sorted({row.get("experiment_type", "") for row in analyzed if row.get("experiment_type")})
    peak_rows = [row for row in analyzed if parse_float(row.get("peak_x")) is not None]
    if not analyzed:
        return (
            "No robust spectral analyses were available for this reporting period. "
            "The report documents processed files and generated figures only. "
            "Further interpretation requires valid parsed spectra."
        )
    peak_range = ""
    if peak_rows:
        peaks = [parse_float(row.get("peak_x")) for row in peak_rows]
        peaks = [value for value in peaks if value is not None]
        peak_range = f" Detected peak positions spanned {min(peaks):.4g} to {max(peaks):.4g} in the relevant spectral units."
    trend_sentence = trends[0] if trends else "No strong cross-sample trend was detected from the available data."
    return (
        f"This report summarizes automated analysis of {len(analyzed)} spectra across "
        f"{', '.join(types) if types else 'the available spectroscopy datasets'}. "
        f"{peak_range} "
        f"{trend_sentence} "
        "All interpretations are derived from the processed manifest and analysis outputs without adding unmeasured results."
    )


def introduction_text() -> str:
    return (
        "Spectroscopic characterization provides rapid evidence for optical transitions, surface chemistry, "
        "emissive behavior, and excited-state dynamics in nanomaterial and sensing studies. "
        "This automated report compiles the processed UV-Vis, photoluminescence, FTIR, lifetime, "
        "and sensing outputs generated by the Smart Lab pipeline."
    )


def experimental_text(results: list[dict]) -> str:
    types = sorted({row.get("experiment_type", "") for row in results if row.get("experiment_type")})
    if not types:
        return "No parsed spectroscopy techniques were available in the analysis manifest."
    descriptions = {
        "UV": "UV-Vis spectra were processed as absorbance versus wavelength traces.",
        "PL": "Photoluminescence spectra were processed as emission or excitation intensity versus wavelength traces.",
        "FTIR": "FTIR spectra were processed as transmittance or absorbance versus wavenumber traces.",
        "lifetime": "Lifetime decay profiles were fitted using a single exponential model where applicable.",
    }
    return " ".join(descriptions.get(kind, f"{kind} files were processed.") for kind in types)


def result_bullets(results: list[dict], limit: int = 12) -> list[str]:
    bullets = []
    for row in results[:limit]:
        source = Path(row.get("source_path", "unknown")).name
        kind = row.get("experiment_type", "unknown")
        peak = format_value(row.get("gaussian_center") or row.get("peak_x"))
        intensity = format_value(row.get("peak_y"))
        fwhm = format_value(row.get("gaussian_fwhm") or row.get("fwhm"))
        tau = format_value(row.get("lifetime_tau"))
        bullets.append(f"{kind}: {source}; peak = {peak}; intensity = {intensity}; FWHM = {fwhm}; tau = {tau}.")
    return bullets


def figure_caption(index: int, plot_row: dict, matching_result: dict | None) -> str:
    kind = plot_row.get("experiment_type", "spectrum")
    if matching_result:
        peak = format_value(matching_result.get("gaussian_center") or matching_result.get("peak_x"))
        return f"Figure {index}: {kind} spectrum showing a detected feature at {peak}."
    return f"Figure {index}: {kind} spectrum generated by the Smart Lab plotting module."


def match_result_for_plot(plot_row: dict, results: list[dict]) -> dict | None:
    source = plot_row.get("source_path", "")
    for row in results:
        if row.get("source_path") == source:
            return row
    return None


def add_paragraph(document: Document, text: str) -> None:
    paragraph = document.add_paragraph(text)
    paragraph.paragraph_format.space_after = Pt(6)
    paragraph.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY


def build_docx(
    target: Path,
    report_kind: str,
    report_date: str,
    results: list[dict],
    plots: list[dict],
    trends: list[str],
) -> None:
    document = Document()
    setup_docx_styles(document)
    title = document.add_paragraph()
    title.style = document.styles["Title"]
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    title.add_run(title_for_report(results, report_kind, report_date))

    document.add_heading("Abstract", level=1)
    add_paragraph(document, abstract_text(results, trends))
    document.add_heading("Introduction", level=1)
    add_paragraph(document, introduction_text())
    document.add_heading("Experimental Section", level=1)
    add_paragraph(document, experimental_text(results))

    document.add_heading("Results and Discussion", level=1)
    for bullet in result_bullets(results):
        document.add_paragraph(bullet, style="List Bullet")
    if trends:
        document.add_heading("Trend Analysis", level=2)
        for trend in trends:
            document.add_paragraph(trend, style="List Bullet")

    figure_index = 1
    for plot_row in plots[:10]:
        plot_path = Path(plot_row.get("plot_path", ""))
        if not plot_path.exists():
            continue
        document.add_picture(str(plot_path), width=Inches(5.8))
        caption = figure_caption(figure_index, plot_row, match_result_for_plot(plot_row, results))
        cap_para = document.add_paragraph(caption)
        cap_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        figure_index += 1

    document.add_heading("Conclusion", level=1)
    conclusion = trends[0] if trends else "The available spectra were processed and plotted; no strong trend was detected."
    add_paragraph(document, f"The automated analysis indicates that {conclusion[0].lower() + conclusion[1:]}")
    document.add_heading("References", level=1)
    add_paragraph(document, "References to be added following Royal Society of Chemistry style as required.")

    target.parent.mkdir(parents=True, exist_ok=True)
    document.save(target)


def build_pdf(
    target: Path,
    report_kind: str,
    report_date: str,
    results: list[dict],
    plots: list[dict],
    trends: list[str],
) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    styles = getSampleStyleSheet()
    styles.add(ParagraphStyle(name="Caption", parent=styles["Normal"], alignment=1, fontSize=9, textColor=colors.HexColor("#333333")))
    story = [
        Paragraph(title_for_report(results, report_kind, report_date), styles["Title"]),
        Spacer(1, 0.15 * inch),
        Paragraph("Abstract", styles["Heading1"]),
        Paragraph(abstract_text(results, trends), styles["BodyText"]),
        Paragraph("Introduction", styles["Heading1"]),
        Paragraph(introduction_text(), styles["BodyText"]),
        Paragraph("Experimental Section", styles["Heading1"]),
        Paragraph(experimental_text(results), styles["BodyText"]),
        Paragraph("Results and Discussion", styles["Heading1"]),
    ]
    for bullet in result_bullets(results):
        story.append(Paragraph(f"- {bullet}", styles["BodyText"]))
    if trends:
        story.append(Paragraph("Trend Analysis", styles["Heading2"]))
        for trend in trends:
            story.append(Paragraph(f"- {trend}", styles["BodyText"]))

    figure_index = 1
    for plot_row in plots[:10]:
        plot_path = Path(plot_row.get("plot_path", ""))
        if not plot_path.exists():
            continue
        story.append(Spacer(1, 0.1 * inch))
        story.append(Image(str(plot_path), width=6.2 * inch, height=3.9 * inch, kind="proportional"))
        story.append(Paragraph(figure_caption(figure_index, plot_row, match_result_for_plot(plot_row, results)), styles["Caption"]))
        figure_index += 1

    story.extend(
        [
            Paragraph("Conclusion", styles["Heading1"]),
            Paragraph(
                trends[0] if trends else "The available spectra were processed and plotted; no strong trend was detected.",
                styles["BodyText"],
            ),
            Paragraph("References", styles["Heading1"]),
            Paragraph("References to be added following Royal Society of Chemistry style as required.", styles["BodyText"]),
        ]
    )
    SimpleDocTemplate(str(target), pagesize=A4, rightMargin=0.7 * inch, leftMargin=0.7 * inch).build(story)


def filter_rows_by_date(rows: Iterable[dict], report_date: dt.date) -> list[dict]:
    return [row for row in rows if row.get("experiment_date") == report_date.isoformat()]


def filter_rows_by_week(rows: Iterable[dict], start: dt.date, end: dt.date) -> list[dict]:
    filtered = []
    for row in rows:
        try:
            value = dt.date.fromisoformat(row.get("experiment_date", ""))
        except ValueError:
            continue
        if start <= value <= end:
            filtered.append(row)
    return filtered


def week_bounds(report_date: dt.date) -> tuple[dt.date, dt.date]:
    start = report_date - dt.timedelta(days=(report_date.weekday() + 1) % 7)
    return start, start + dt.timedelta(days=6)


def load_trends(reports_dir: Path) -> list[str]:
    trends_path = reports_dir / "trends_summary.txt"
    if not trends_path.exists():
        return []
    return [line.strip("- ").strip() for line in trends_path.read_text(encoding="utf-8").splitlines() if line.strip()]


def generate_all_reports(output_dir: Path, report_date: dt.date | None = None) -> dict[str, str]:
    report_date = report_date or dt.date.today()
    manifests_dir = output_dir / "outputs" / "manifests"
    reports_dir = output_dir / "outputs" / "reports"
    results = read_csv_rows(manifests_dir / "analysis_results.csv")
    plots = read_csv_rows(manifests_dir / "plot_manifest.csv")
    trends = load_trends(reports_dir)

    daily_results = filter_rows_by_date(results, report_date)
    daily_plots = filter_rows_by_date(plots, report_date)
    week_start, week_end = week_bounds(report_date)
    weekly_results = filter_rows_by_week(results, week_start, week_end)
    weekly_plots = filter_rows_by_week(plots, week_start, week_end)
    iso_year, iso_week, _ = report_date.isocalendar()

    outputs = {
        "daily_docx": reports_dir / f"daily_report_{report_date.isoformat()}.docx",
        "daily_pdf": reports_dir / f"daily_report_{report_date.isoformat()}.pdf",
        "weekly_docx": reports_dir / f"weekly_report_{iso_year}-W{iso_week:02d}.docx",
        "weekly_pdf": reports_dir / f"weekly_report_{iso_year}-W{iso_week:02d}.pdf",
    }
    build_docx(outputs["daily_docx"], "daily", report_date.isoformat(), daily_results, daily_plots, trends)
    build_pdf(outputs["daily_pdf"], "daily", report_date.isoformat(), daily_results, daily_plots, trends)
    build_docx(outputs["weekly_docx"], "weekly", f"{week_start.isoformat()} to {week_end.isoformat()}", weekly_results, weekly_plots, trends)
    build_pdf(outputs["weekly_pdf"], "weekly", f"{week_start.isoformat()} to {week_end.isoformat()}", weekly_results, weekly_plots, trends)
    return {key: str(value) for key, value in outputs.items()}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--date", help="Report date as YYYY-MM-DD; defaults to today")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    report_date = dt.date.fromisoformat(args.date) if args.date else dt.date.today()
    outputs = generate_all_reports(args.output_dir, report_date)
    for label, path in outputs.items():
        print(f"{label}: {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
